### ISSUE TITLE
[Feat] Helm Chart Install.

### ISSUE THREAD

**Issue by Koooooo-7** [Koooooo-7/KaViewer#2]
TODO: 
Deploy with Helm.

**Comment by Eva-0901** [comment]
你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！你凭什么可以不理我！！！！！你还有理了！！！！！！！
